server:
  port: 9090

spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:h2:mem:url-shortener
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

url:
  shortener:
    short-code:
      length: 6
    alias-check:
      offset: 500
    short-code-check:
      offset: 500

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui