server:
  port: 9090

spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:mysql://mysqldb:3306/url-shortener-db?useSSL=false
    username: root
    password: rootpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

url:
  shortener:
    short-code:
      length: 6
    alias-check:
      offset: 500
    short-code-check:
      offset: 500

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui